apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mongodb-configmap
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  database_URL: {{ .Release.Name }}-mongodb-service
